{"name": "test006", "status": "failed", "statusDetails": {"message": "AssertionError: assert (2 + 3) == 4", "trace": ">   ???\nE   assert (2 + 3) == 4\n\n/Users/mac/PycharmProjects/pythonProject/pytest/class_14_allure_uploadErrScreenshot/testcase/test_02.py:31: AssertionError"}, "attachments": [{"name": "可以自定义的图片名称", "source": "608535f9-0b94-4a56-a0a8-fb69670344fc-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "586488f0-2c20-4cad-a659-0268f382dab5-attachment.txt", "type": "text/plain"}], "start": 1714048698340, "stop": 1714048698340, "uuid": "deec86e2-525d-467f-b845-14c37d4f52d2", "historyId": "16c965e2c280b41f7878adaa540ee168", "testCaseId": "16c965e2c280b41f7878adaa540ee168", "fullName": "testcase.test_02#test006", "labels": [{"name": "feature", "value": "模块3"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_02"}, {"name": "host", "value": "haiyang.xie"}, {"name": "thread", "value": "13378-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_02"}]}